sudo: true
language:
  - python
  - node_js
python: 3.5
node_js: 8

cache: pip

services:
  - docker

before-install:
  - sudo apt-get update
  - sudo apt-get update && apt-get install build-essential curl wget -y
  - sudo curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - sudo apt-get install -y nodejs

  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn

  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
  - sudo apt-get update 
  - sudo apt-get install google-chrome-stable

install:
  - pip install -r requirements.txt

script:
  - make lint_backend
  - make build_front
  - make download_data
  - make create_db
  - cd backend && docker build -t munch . && cd ..

  - docker-compose up -d
  - cd e2e && yarn install --flat && node main.js && cd ..

deploy:
  provider: script
  script: docker tag munch:latest "przemyslawjanpietrzak/munch:$TRAVIS_BRANCH" && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "przemyslawjanpietrzak/munch:$TRAVIS_BRANCH"
  on:
    branch:
      - develop
      - master
