sudo: true
language:
  - python
  - node_js
python: 3.5
node_js: 8

cache: pip

services:
  - docker

before-install:
  - sudo apt-get update
  - sudo apt-get update && apt-get install build-essential curl wget -y
  - sudo curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - sudo apt-get install -y nodejs

script:
  python -c 'import scripts.create_db'
  docker build -t munch .

