sudo: true
language:
  - python
python: 3.5

cache: pip

services:
  - docker

before-install:
  - sudo apt-get update

install:
  - pip install -r requirements.txt

script:
  - make lint_backend

  - make build_front
  - cp -r frontend/dist nginx

  - make download_data
  - make create_db
  - cd backend && docker build -t munch . && cd ..

  - docker-compose up -d

  - docker run -v ~/munch/e2e/main.test.js:/code/main.test.js przemyslawjanpietrzak/munch-e2e

  - cd e2e && yarn && yarn test && cd ..

deploy:
  provider: script
  script: docker tag munch:latest "przemyslawjanpietrzak/munch:$TRAVIS_BRANCH" && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "przemyslawjanpietrzak/munch:$TRAVIS_BRANCH"
  on:
    branch:
      - develop
      - master
