language: python
python: 3.5
env:
  matrix:
  - ENVIRONMENT=CI
  MUNCH_AWS_SECRET_ACCESS_KEY:
    secure: wWQlknoJKUVFhHFo7atKUKkapzka8uMhSnZjTRWbBxfhlR6HCU2niXyzUlZLJu3/c7xQRqAPAEzKcq3d8+w6WNFgj/nRpzhynXeYdqko7hwvKHZw0jJR9G6fprvTzS+10s+wBbdhL2WmIWpuIzckS8SRDNJiybUNtw+tzeHvrMeC0D1J2iXBA3CBcCS0TdEGG89j/QBUBwLsBFWLVVXUt+uxqVwcRgR25Pko2+JNtQFnr7SXQGvHzkB58F1XEsGwhijO+li1gZY/aH8eqk+vg5JML9OVECQ1OIZ0IS5NMxGYg1xA4OcGZuj/OonLeOahp4uXS2mdrQojwR1Th76uwCNLpNgkPRKauReysyJOPVNvuPc29iCQpKYPm9bHQKtqGIH74Afi1lWNmdDhXi+TRpVOrPTD0pGtGxw/8LPJ5AKdnQqTfuctxXlqZjZVfZ+iswemzAEPsfOOEGy0D9WCkLmKfoCDBgIeYuIU4F5HZvpANb2sPAqjyrhaKGbYuXP2e7/FDB0qWh4KxOgI8pKsixAvmwbMDGghPLdYOJJnQ9sawIV9QF4TWBn8B2Jh0qCNSoPF/nWByfdP9rw3Lf56XocD8zowMp4O1hKzhVulyLhsTzQhPVgXyZBvEHOeH3gAfZaWTEJgjQJAxwgr22QKbKSy7RznzFMD43OtZ3aHxFk=
  MUNCH_AWS_ACCESS_KEY_ID:
    secure: ElZyPqDQxsS1f9KOzbEtOjPFk5KDquIhd6AxnTQbobNg3ihV16Or07Te2eTZ3wjbwdUzSDvbKyYVd6m06E8a5ggjzsM3Npx9GmqGyCBJmNoDSozofTM+4gBg1Y2pNrM0AxCrzGkiRhzTlRi+MtZLMRNVlxvQR3wsYft70B8Q8eWuSyIhuxEHaY4mnDVZuV9I+NgTb29N81H+wZ5c3IhcuTPePBBXh4wSq+X2AMueUAJ5ZVMgsoLMSJ8wt4UYi1wcdaFIXrV8l/Z8FVt0CsvQjMh0QUyzc/oq2pX8GMUPLqvhRAXLIZ5WC4Dj9ja0uXj135CRUVx+aGBCYxqXXhlfO8ZUhdXeFXLGZhYvZoRPG6vWMNnfzw3b2hhD8ZfiNDliLwzs4joThtHv5vgePpMHOy2eL4DbmnPOUuaFqDkC3WiIPYRZcNqP1uNf9749tF6S/KZfdcgqwXibGqqctvLAd4pFhqBjTQUOEAoC9hV/nK+aqwkFA6gy042SRFz7pGflXtX+bOsWqURcJRGT3vEWN/BEuMYDi5SH4XHWCCxWi1MeYX3RBYXubPxRL694PCA48zSsoq6QsY5X7NzL11BegsoTc9MttJQ2zsiexvopxBHf3W8pZgFANVNhja3arw2jguQwRk93Qc5uu/4+mTfNWLsmo5c01LJL0V60s+50Zh0=
install:
- make install
script:
- make clean
- make download_data
- make create_db
- make train
- make test
