language:
  - python
python: 3.5
cache: pip
install:
  - virtualenv -p python3 ~/.virtualenvs/munch
  - source ~/.virtualenvs/munch/bin/activate
  - make install
  - make install-dev
script:
  - make create_db
  - make train
  - make test
