version: '3.3'
services:

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - app
        links:
            - app
           
    app:
        restart: always
        image: "przemyslawjanpietrzak/munch:stable"
        expose:
            - "8000"
        ports:
            - 8080:8080
        command: gunicorn api.main:application --workers 2 --bind 0.0.0.0:8000
