version: '3.3'
services:

    nginx:
        image: nginx
        ports:
            - "80:80"
        depends_on:
            - munch
        links:
            - munch
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    munch:
        restart: always
        image: "munch"
        expose:
            - "8000"
        ports:
            - 8080:8080
        command: gunicorn main:application --workers 2 --bind 0.0.0.0:8000
