version: '3'
services:
    web:
        restart: always
        image: "przemyslawjanpietrzak/munch:stable"
        expose:
            - "8000"
        network_mode: "host"

    nginx:
        image: nginx
        ports:
            - 8080:8080
            - "80:80"
        volumes:
            - ./nginx/:/etc/nginx/conf.d
        depends_on:
            - web
        
            
            
