version: '3'
services:
    web:
        build: .
        ports:
            - "8000:8000"
            
    nginx:
        image: "nginx:alpine"
        build: ./nginx
        links:
            - web
        ports:
            - "80:80"