version: '3.3'
services:

    nginx:
        image: nginx
        ports:
            - "80:80"
        depends_on:
            - munch
            - push-service
        links:
            - munch
            - push-service
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/dist:/www/static

    munch:
        restart: always
        image: "przemyslawjanpietrzak/munch:develop"
        expose:
            - "8000"
        ports:
            - 8080:8080
        command: gunicorn main:application --workers 2 --bind 0.0.0.0:8000

    push-service:
        restart: always
        image: node:8
        working_dir: /code
        ports:
            - "3000:3000"
        volumes:
            - ./push-service:/code/
            # - ./push-service/server.js:/code/server.js
            # - ./new-version.txt:/code/new-version.txt
        expose:
            - "3000"
        command: node server.js