version: '3'
services:
    web:
        build: .
        links:
            - nginx
        ports:
            - "8000:8000"
            
    nginx:
        image: "nginx:alpine"
        links:
            - web
        ports:
            - "80:80"