---
- hosts: localhost
  vars:
    bucket_name: munch-bucket1
    profile_name: munch
    download_dirty_data: False

  tasks: 
    - name: Craete dir
      command: mkdir -p data
    
    - name: Download clean data
      s3:
        bucket: "{{ bucket_name }}"
        object: data.csv
        dest: data/data.csv
        mode: get
        profile: "{{ profile_name }}"
        region: eu-central-1

    - name: download dirty data
      s3:
        bucket: "{{ bucket_name }}"
        object: data.csv
        dest: data/news.xls
        mode: get
        profile: "{{ profile_name }}"
        region: eu-central-1
      when: download_dirty_data