---

- hosts: localhost
  vars:
    - venv_name: munch
    - venv_dir: ~/venvs/munch
    - venv_bin: ~/venvs/munch/bin

  tasks:

    - name: Safe system upgrade via apt
      apt:
        name: aptitude
    
    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items:
        - python-pip
        - python3-dev
        - build-essential

    - name: Install global python requirements
      pip: name={{ item }}
      with_items:
        - virtualenv
        - virtualenvwrapper
  
    - name: Make a virtualenv
      command: virtualenv "{{ venv_dir }}" -p python3

    - name: Install depencenccies
      pip: requirements=~/code/munch/requirements.txt virtualenv="{{ venv_dir }}"
    
    - name: Download spiCy EN
      command: "{{ venv_bin }}/python -m spacy download en"

    - name: Create database
      command: "{{ venv_bin }}/python -m scripts.create_db"

    - name: Train model
      command: "{{ venv_bin }}/python text_recognition/train.py"

    - name: Run server
      command: "{{ venv_bin }}/gunicorn --reload api.main:application"