---

- hosts: localhost
  vars:
    - venv_name: munch
    - venv_dir: ~/venvs/munch
    - venv_bin: ~/venvs/munch/bin

    - bucket_name: munch-bucket1
    - profile_name: munch

    - ansible_build: True
    - download_dirty_data: False

  tasks:

    - name: Safe system upgrade via apt
      apt:
        name: aptitude
    
    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items:
        - python-pip
        - python3-dev
        - build-essential

    - name: Install global python requirements
      pip: name={{ item }}
      with_items:
        - virtualenv
        - virtualenvwrapper
  
    - name: Make a virtualenv
      command: virtualenv "{{ venv_dir }}" -p python3
      when: ansible_build

    - include: download_files.yaml
        
    - name: Install depencenccies
      pip: requirements=~/code/munch/requirements.txt virtualenv="{{ venv_dir }}"
      when: ansible_build
    
    - name: Download spiCy EN
      command: "{{ venv_bin }}/python -m spacy download en"
      when: ansible_build

    - name: Create database
      command: "{{ venv_bin }}/python -m scripts.create_db"
      when: ansible_build

    - name: Train model
      command: "{{ venv_bin }}/python text_recognition/train.py"
      when: ansible_build

    - include: test.yaml


