---
- hosts: localhost
  # vars:
  #   bucket_name: munch-bucket1
  #   profile_name: munch

  tasks:
  - name: download clean data
    s3:
      bucket: munch-bucket1
      object: data.csv
      dest: data/data.csv
      mode: get
      profile: munch
      region: eu-central-1
      