---

- hosts: localhost
  vars:
    - venv_name: munch

  tasks:

    - name: Safe system upgrade via apt
      apt:
        name: aptitude
    
    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items:
        - python-pip
        - python3-dev
        - build-essential

    - name: Install global python requirements
      pip: name={{ item }}
      with_items:
        - virtualenv
        - virtualenvwrapper
    

    - name: Make a virtualenv
      shell: . /usr/share/virtualenvwrapper/virtualenvwrapper.sh && mkvirtualenv {{ venv_name }} --python=/usr/bin/python3
      args:
        executable: /bin/bash

              