- hosts: munch
  remote_user: ubuntu
  gather_facts: no
  vars_files:
    - vars.yaml
  vars:
    ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"
    base_dir: "{{ playbook_dir }}/.."

  pre_tasks:
    - name: install python2 for ansible
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Echo a hello message
      command: echo hello

    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items:
        - git
        - python-pip
        - python3-dev
        - build-essential
        - python-virtualenv
      when: not travis
      become: true

    - name: Make a virtualenv
      command: virtualenv "{{ venv_dir }}" -p python3
      when: new_build

    - name: Clone repo
      git:
        repo: 'https://github.com/przemyslawjanpietrzak/munch'
        dest: ./munch
        update: yes
        
    - name: Install depencencies
      pip: requirements=~/munch/requirements.txt virtualenv="{{ venv_dir }}"
      when: new_build

    - name: mkdir
      command: "mkdir -p {{ item }}"
      with_items: 
        - ~/munch/text_recognition/models/default/model
        - ~/munch/data

    - name: Download data
      get_url: url={{ bucket_url }}/data.csv dest=~/munch/data

    - name: Download model
      get_url: "url={{ item }} dest=~/munch/text_recognition/models/default/model"
      with_items:
        - "{{ bucket_url }}/crf_model.pkl"
        - "{{ bucket_url }}/entity_synonyms.json"
        - "{{ bucket_url }}/metadata.json"
        - "{{ bucket_url }}/intent_classifier.pkl"
        - "{{ bucket_url }}/training_data.json"
  
    - name: Create database
      command: make -C munch/ create_db

    - name: Run server
      command: make -C munch/ server
